plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - web.md
remote_theme: "pages-themes/primer"
title: COVID-19, dati comuni siciliani
description: un repository dove raccogliere dati sui comuni siciliali
lang: it-IT
